### ISSUE TITLE
SDK 34 compatibility

### ISSUE THREAD

**Issue by jacobg** [ns0m/cordova-plugin-ns0m-nfc#12]
Android 14 (SDK 34) removes the Android Beam feature (i.e., NDEF push), so it should be removed from this plugin:
https://developer.android.com/sdk/api_diff/34/changes/android.nfc.NfcAdapter

**Comment by ath0mas** [comment]
Already planned. Checking and discussing the changes directly in parent repo and PR https://github.com/chariotsolutions/phonegap-nfc/pull/508.
When ok for me, I'll do the PR here and merge, before a new release to follow quickly.

**Comment by ath0mas** [comment]
Released in [v1.3.0-5](https://github.com/ns0m/cordova-plugin-ns0m-nfc/releases/tag/v1.3.0-5), published to [cordova-plugin-ns0m-nfc](https://www.npmjs.com/package/cordova-plugin-ns0m-nfc).
